all:
	gcc -Iinclude/ src/app.c src/camera.c src/main.c src/scene.c src/texture.c src/utils.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lobj -lopengl32 -lm -o suti.exe -Wall -Wextra -Wpedantic 


